frontend:
   build: "frontend/"
   dockerfile: "Dockerfile"
   environment:
      - EMBER_ENV=development
   ports:
      - "4200:4200"
      - "49152:49152"

postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: backend
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - backend-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - backend-redis:/var/lib/redis/data

backend:
  build: backend/
  dockerfile: "Dockerfile"
  links:
    - postgres
    - redis
  volumes:
    - ./backend:/backend
  ports:
    - '8000:8000'
  env_file:
    - backend/.backend.env

sidekiq:
  build: backend/
  dockerfile: "Dockerfile"
  command: bundle exec sidekiq -C backend/config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - ./backend:/backend
  env_file:
    - backend/.backend.env
