postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: backend
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - backend-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - backend-redis:/var/lib/redis/data

backend:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/backend
  ports:
    - '8000:8000'
  env_file:
    - .backend.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/backend
  env_file:
    - .backend.env
