source 'https://rubygems.org'

# gem for server
gem 'unicorn', '~> 4.9'

# gem for postgresql
gem 'pg', '~> 0.18.3'

# gem for task manager and dependencies
gem 'sidekiq', '~> 4.0.1'
gem 'redis-rails', '~> 4.0.0'

# gem for rails and rails api
gem 'rails', '4.2.6'
gem 'rails-api'
gem 'spring', :group => :development

# gem for creating json
gem 'active_model_serializers', '0.9.3'

# gem for github integration
gem "octokit", "~> 4.0"

# gem for authentication
gem 'devise', '~> 3.5', '>= 3.5.6'
